{% set name = "z3-solver" %}
{% set version = "4.12.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# Removing this for now. Going to try install from Wheel
# source:
#   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/z3-solver-{{ version }}.tar.gz
#   sha256: 65ab47a0a8ef0bfb80db0670775beb11b32c3c0ae4b35943e44121f4af7ef411

build:
  script: {{ PYTHON }} -m pip install z3-solver==4.12.2.0 -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=46.4.0
    - wheel
    - cmake
    - pip
  run:
    - python

test:
  imports:
    - z3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Z3Prover/z3
  summary: an efficient SMT solver library
  license: MIT
  license_file: core/LICENSE.txt

extra:
  recipe-maintainers:
    - tenzinhl
